# Generated by Erlang.mk. Edit at your own risk!

src/ht2_tests.erl:: src/bs01.erl src/bs02.erl src/bs03.erl; @touch $@
src/p01_tests.erl:: src/p01.erl; @touch $@
src/p02_tests.erl:: src/p02.erl; @touch $@
src/p03_tests.erl:: src/p03.erl; @touch $@
src/p04_tests.erl:: src/p04.erl; @touch $@
src/p05_tests.erl:: src/p05.erl; @touch $@
src/p06.erl:: src/p05.erl; @touch $@
src/p06_tests.erl:: src/p06.erl; @touch $@
src/p07_tests.erl:: src/p07.erl; @touch $@
src/p08_tests.erl:: src/p08.erl; @touch $@
src/p09_tests.erl:: src/p09.erl; @touch $@
src/p10_tests.erl:: src/p10.erl; @touch $@
src/p11_tests.erl:: src/p11.erl; @touch $@
src/p12_tests.erl:: src/p12.erl; @touch $@
src/p13_tests.erl:: src/p13.erl; @touch $@
src/p14_tests.erl:: src/p14.erl; @touch $@
src/p15_tests.erl:: src/p15.erl; @touch $@

COMPILE_FIRST += p09 p08 p07 p05 p06 p04 p15 p14 p13 p12 p11 p10 p03 bs03 p02 bs02 p01 bs01
